"""Generates the POSIX-sh status line script.

Deliberately NOT Python: Claude Code re-renders the status line continuously,
and a ~400 ms Python interpreter start in that loop is unacceptable. The script
needs only `jq`; when `jq` is absent it prints nothing and exits 0.

The script has two jobs:
  1. render  `observed → recommended · model · ctx%`
  2. sense   record the live effort level, which is visible on NO other surface
"""
from __future__ import annotations

import stat
from pathlib import Path

from . import paths

_SCRIPT = r"""#!/usr/bin/env sh
# Generated by `skill-advisor install`. Do not edit — regenerate instead.
set -u

CACHE="${SKILL_ADVISOR_CACHE_HOME:-${XDG_CACHE_HOME:-$HOME/.cache}/skill-advisor}"

command -v jq >/dev/null 2>&1 || exit 0
input=$(cat 2>/dev/null) || exit 0
[ -n "$input" ] || exit 0

observed=$(printf '%s' "$input" | jq -r '.effort.level // empty' 2>/dev/null) || exit 0
session=$(printf '%s' "$input" | jq -r '.session_id // empty' 2>/dev/null)
model=$(printf '%s' "$input" | jq -r '.model.display_name // empty' 2>/dev/null)
ctx=$(printf '%s' "$input" | jq -r '.context_window.used_percentage // empty' 2>/dev/null)

# ctx must be numerically well-formed, not just the right character set:
# digits with at most one decimal point, and at least one digit (reject "",
# non-[0-9.] chars, "a.b.c"-style multi-dot, and a bare "." with no digits).
case "$ctx" in
  ''|*[!0-9.]*|*.*.*) ctx="" ;;
esac
case "$ctx" in
  *[0-9]*) : ;;
  *) ctx="" ;;
esac

# --- sensor: the only place live effort is visible ---
if [ -n "$observed" ]; then
  if mkdir -p "$CACHE" 2>/dev/null; then
    tmp="$CACHE/observed-effort.json.tmp.$$"
    if jq -n --arg session "$session" --arg level "$observed" --argjson ts "$(date +%s)" \
         '{session_id:$session, level:$level, ts:$ts}' > "$tmp" 2>/dev/null; then
      mv "$tmp" "$CACHE/observed-effort.json" 2>/dev/null || rm -f "$tmp" 2>/dev/null
    fi
  fi
fi

recommended=""
if [ -f "$CACHE/effort.json" ]; then
  recommended=$(jq -r '.level // empty' < "$CACHE/effort.json" 2>/dev/null)
fi

colour() {
  case "$1" in
    low)       printf '\033[34m' ;;
    medium)    printf '\033[36m' ;;
    high)      printf '\033[32m' ;;
    xhigh|max) printf '\033[33m' ;;
    ultracode) printf '\033[35m' ;;
    *)         printf '' ;;
  esac
}
RESET='\033[0m'

out=""
if [ -n "$observed" ]; then
  out="$(colour "$observed")${observed}${RESET}"
  # ultracode ranks equal to xhigh, so xhigh-observed never disagrees with it
  if [ -n "$recommended" ] && [ "$recommended" != "$observed" ] \
     && ! { [ "$recommended" = "ultracode" ] && [ "$observed" = "xhigh" ]; } \
     && [ "$observed" != "max" ]; then
    out="$out \033[2m→\033[0m $(colour "$recommended")${recommended}${RESET}"
  fi
fi

[ -n "$model" ] && { [ -n "$out" ] && out="$out \033[2m·\033[0m $model" || out="$model"; }
[ -n "$ctx" ] && out="$out \033[2m·\033[0m ctx $(printf '%.0f' "$ctx")%"

[ -n "$out" ] && printf '%b\n' "$out"
exit 0
"""


def script_text() -> str:
    """The full script body. Pure — safe to snapshot in tests."""
    return _SCRIPT


def write_script() -> Path:
    """Write the script to `paths.statusline_script()` and chmod it executable."""
    paths.ensure_dirs()
    target = paths.statusline_script()
    target.write_text(script_text(), encoding="utf-8")
    target.chmod(target.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return target
